# Generated by Django 3.1.4 on 2021-07-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_on',
            field=models.DateField(auto_now=True),
        ),
    ]
